adherent_coupon_list:
    path:     /list
    defaults: { _controller: backAdherentBundle:Coupon:list}

adherent_coupon_delete:
    path:     /delete/{id}
    defaults: { _controller: backAdherentBundle:Coupon:Delete }

adherent_coupon_ajouter:
    path:     /ajouter
    defaults: { _controller: backAdherentBundle:Coupon:ajouter,id:null }

adherent_coupon_modifier:
    path:      /modifier/{id}
    defaults: { _controller: backAdherentBundle:Coupon:ajouter }