back_general_produit_list:
    path:     /list
    defaults: { _controller: backGeneralBundle:Produit:list}

back_general_produit_delete:
    path:     /delete/{id}
    defaults: { _controller: backGeneralBundle:Produit:Delete }

back_general_produit_ajouter:
    path:     /ajouter
    defaults: { _controller: backGeneralBundle:Produit:ajouter,id:null }

back_general_produit_modifier:
    path:      /modifier/{id}
    defaults: { _controller: backGeneralBundle:Produit:ajouter }