front_general_accueil:
    path:     /
    defaults: { _controller: frontGeneralBundle:Homepage:accueil }

front_general_contact:
    path:     /contact
    defaults: { _controller: frontGeneralBundle:Homepage:contactUs }

front_super_marches:
    path:     /supermarches
    defaults: { _controller: frontGeneralBundle:Supermarche:list }

front_super_marches_details:
    path:     /supermarches/{id}
    defaults: { _controller: frontGeneralBundle:Supermarche:details }

front_pannier_add_product:
    path:     /pannier/addproduct/{idProduit}/{idSupermarche}
    defaults: { _controller: frontGeneralBundle:Pannier:addProduit }

front_pannier_add_coupon:
    path:     /pannier/addcoupons/{idCoupon}/{idSupermarche}
    defaults: { _controller: frontGeneralBundle:Pannier:addcoupon }

front_pannier_coupons:
    path:     /pannier/coupons
    defaults: { _controller: frontGeneralBundle:Pannier:listCoupons }

front_pannier_produits:
    path:     /pannier/produits
    defaults: { _controller: frontGeneralBundle:Pannier:listProduits }

front_pannier_delete_coupon:
    path:     /pannier/coupon_delete/{id}
    defaults: { _controller: frontGeneralBundle:Pannier:deleteCoupon }

front_pannier_delete_produit:
    path:     /pannier/produit_delete/{id}
    defaults: { _controller: frontGeneralBundle:Pannier:deleteProduit }

front_pannier_pdf_produit:
    path:     /pannier/produit_pdf
    defaults: { _controller: frontGeneralBundle:Pannier:produitsPdf }

front_pannier_pdf_coupon:
    path:     /pannier/coupon_pdf
    defaults: { _controller: frontGeneralBundle:Pannier:couponsPdf }
