<?php

namespace back\GeneralBundle\Repository;

/**
 * CouponRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CouponRepository extends \Doctrine\ORM\EntityRepository
{
    public function search($data)
    {
        $query = $this->createQueryBuilder("p");

        $query->select("p");
        if (isset($data['produit']) && $data['produit'] != null)
            $query
                ->andWhere("p.produit = :idProduit")
                ->setParameter("idProduit", $data['produit']->getId());
        return $query->getQuery()->getResult();

    }
}
