<?php

namespace back\GeneralBundle\Repository;

/**
 * GovernoratRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GovernoratRepository extends \Doctrine\ORM\EntityRepository
{
}
