<?php
namespace back\GeneralBundle\Repository;
use back\GeneralBundle\Entity\User;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function search($data,User $user=null)
    {
        $query = $this->createQueryBuilder("p");
        $query->select("p")
            ->innerJoin("p.supermarche","sp");

        if (isset($data['marque']) && $data['marque'] != null)
            $query
                ->andWhere("p.marque = :idMarque")
                ->setParameter("idMarque", $data['marque']->getId());

        if(isset($user) and  $user->getSupermarche())
            $query
                ->andWhere("sp.id = :superMacheId")
                ->setParameter("superMacheId",$user->getSupermarche()->getId());
        return $query->getQuery()->getResult();
    }

    public function getProduits($idSupermarche,$idCategorie)
    {
        $query = $this->createQueryBuilder("p");
        $query
            ->join("p.supermarche","s")
            ->join("p.categories","c")
            ->where("s.id = :idSupermarche")
            ->andWhere("c.id = :idCategory")
            ->setParameters(array(
                "idCategory"=>$idCategorie,
                "idSupermarche"=>$idSupermarche
            ));
        return $query->getQuery()->getResult();
    }


}
