<?php

namespace back\GeneralBundle\Repository;

/**
 * RecetteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecetteRepository extends \Doctrine\ORM\EntityRepository
{
    public function search($data)
    {
        $query = $this->createQueryBuilder("r");

        $query->select("r");
        if (isset($data['produit']) && $data['produit'] != null)
            $query
                ->join("r.produit","p")
                ->andWhere("p.id = :idProduit")
                ->setParameter("idProduit", $data['produit']->getId());
        return $query->getQuery()->getResult();

    }
}
