<?php

namespace back\GeneralBundle\Repository;

/**
 * SupermarcheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupermarcheRepository extends \Doctrine\ORM\EntityRepository
{
}
