back_general_homepage:
    path:     /
    defaults: { _controller: backGeneralBundle:Default:dashboard }

back_general_referentiel:
    resource: "@backGeneralBundle/Resources/config/routing/referentiel.yml"
    prefix:   /ref

back_general_client:
    resource: "@backGeneralBundle/Resources/config/routing/client.yml"
    prefix:   /client

back_general_adherent:
    resource: "@backGeneralBundle/Resources/config/routing/adherent.yml"
    prefix:   /adherent

back_general_supermarche:
    resource: "@backGeneralBundle/Resources/config/routing/supermarche.yml"
    prefix:   /supermarche

back_general_marque:
    resource: "@backGeneralBundle/Resources/config/routing/marque.yml"
    prefix:   /marque

back_general_rayon:
    resource: "@backGeneralBundle/Resources/config/routing/rayon.yml"
    prefix:   /rayon

back_general_categorie:
    resource: "@backGeneralBundle/Resources/config/routing/categorie.yml"
    prefix:   /categorie